<div class="container">
  <h1>
    <span>N</span>
    <span>o</span>
    <span>t</span>
    <span>r</span>
    <span>e</span>
    &nbsp
    <span>é</span>
    <span>c</span>
    <span>o</span>
    <span>l</span>
    <span>e</span>
    <span>!</span>
  </h1>
  <h2 class="text-center formTitre">Les horaires de l'école</h2>
  <p class="text-center perso fs-4">Lundi et Mardi : 8h20 - 11h30 et 13h20 - 16h30</p>
  <p class="text-center perso fs-4">Mercredi : Fermé</p>
  <p class="text-center perso fs-4">Jeudi et Vendredi : 8h20 - 11h30 et 13h20 - 16h30</p>
  <p class="text-center perso fs-4">Samedi et Dimanche : Fermé</p>
  <h2 class="text-center formTitre">Les coordonnées de l'école</h2>
  <p class="text-center perso fs-4">Adresse : Pl. du Champ de Mars, 01500 Ambérieu-en-Bugey</p>
  <p class="text-center perso fs-4">Téléphone : 0474380712</p>
  <p class="text-center perso fs-4">Email : ce.0011207g@ac-lyon.fr</p>
  <h2 class="text-center formTitre">Où trouver l'école</h2>
  <div class="d-flex justify-content-center">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2773.5923623116005!2d5.355298615748038!3d45.95942700828233!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478b51891111261b%3A0x6478721d92937a5!2s%C3%89cole%20El%C3%A9mentaire%20Jules%20Ferry!5e0!3m2!1sfr!2sfr!4v1677433110279!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>
</div>