<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h1 class="text-center mb-4">Mon compte</h1>
            <?php if (isset($error)) { ?>
                <div class="alert alert-danger" role="alert">
                    <?php echo $error ?>
                </div>
            <?php } ?>
            <?php if (isset($success)) { ?>
                <div class="alert alert-success" role="alert">
                    <?php echo $success ?>
                </div>
            <?php } ?>
            <form id="MAJParent" method="POST" class="form-login">
                <div class="mb-3">
                    <label for="nom" class="form-label">Nom</label>
                    <input type="text" class="form-control" id="nom" name="nom" placeholder="Votre nom" value="<?php if (isset($success)) {
                                                                                                                    echo $parent->getNom();
                                                                                                                } else {
                                                                                                                    echo $parentSelect['nom'];
                                                                                                                } ?>" required>
                </div>
                <div class="mb-3">
                    <label for="prenom" class="form-label">Prénom</label>
                    <input type="text" class="form-control" id="prenom" name="prenom" placeholder="Votre prénom" value="<?php if (isset($success)) {
                                                                                                                            echo $parent->getPrenom();
                                                                                                                        } else {
                                                                                                                            echo $parentSelect['prenom'];
                                                                                                                        } ?>" required>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Adresse e-mail</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Votre adresse e-mail" value="<?php if (isset($success)) {
                                                                                                                                    echo $parent->getEmail();
                                                                                                                                } else {
                                                                                                                                    echo $parentSelect['email'];
                                                                                                                                } ?>" required>
                </div>
                <div class="mb-3">
                    <label for="motdepasse" class="form-label">Mot de passe</label>
                    <input type="password" class="form-control" id="cPassword" name="motdepasse" placeholder="Votre mot de passe (actuel si vous ne souhaitez pas le changer)" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{12,}$" required>
                    <div class="form-text">Le mot de passe doit contenir au moins 12 caractères, dont une lettre minuscule, une lettre majuscule, un chiffre et un caractère spécial.</div>
                    <div> <input type="checkbox" id="showPassword">
                        <label for="showPassword" id="labelShowPassword">Afficher le mot de passe</label>
                    </div>
                </div>

                <div class="d-flex justify-content-between">
                    <button name="modifier" type="submit" class="button me-2">Enregistrer</button>
                    <button name="delete_compte" type="submit" class="button" onclick="return confirm('Êtes-vous sûr de vouloir supprimer votre compte ?')">Supprimer mon compte</button>
                </div>

            </form>

        </div>
    </div>
</div>
