   <div class="content-page">
       <div class="content">

           <!-- Start Content-->
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box">

                           <h4 class="page-title">Ajouter une absence pour un enseignant</h4>
                       </div>
                   </div>
               </div>
               <!-- end page title -->

               <div class="row">
                   <div class="col-12">
                       <div class="card-box">
                           <?php if ($ajout_ok == 1) { ?>
                               <div class="alert alert-success" role="alert">
                                   <?php echo "L'absence a bien été ajouter" ?>
                               </div>
                           <?php } ?>
                           <form class="form-horizontal" method="POST">
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="debut">Date de début<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="date" class="form-control" id="debut" name="debut" required>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="fin">Date de fin<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="date" class="form-control" id="fin" name="fin" required>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label for="hori-pass1" class="col-sm-2 col-form-label">Enseignant<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <select name="id_enseignant" class="form-control" required>
                                           <option value="">Sélectionner un enseignant</option>
                                           <?php foreach ($listeEnseignant as $enseignant) { ?>
                                               <option name="id_enseignant" value="<?php echo $enseignant['id'] ?>"><?php echo $enseignant['nom'] ?> </option>

                                               <!--<input type="text" class="form-control" id="simpleinput" name="categorie_id" value="ordinateur"> -->

                                           <?php } ?>
                                       </select>
                                   </div>
                               </div>
                       <button type="submit" class="btn btn-primary" name="ajouter">Ajouter</button>
                       </form>
                       </div>



                   </div> <!-- end card-box -->
               </div><!-- end col -->
           </div>
           <!-- end row -->




       </div> <!-- container-fluid -->

   </div> <!-- content -->

   <!-- Footer Start -->
   <footer class="footer">
       <div class="container-fluid">
           <div class="row">
               <div class="col-md-12 text-center">
                   2023 &copy; thème Greeva, créé par Coderthemes, modifié par Véricel Grégory. 
               </div>
           </div>
       </div>
   </footer>
   <!-- end Footer -->

   </div>
   <!-- Vendor js -->
   <script src="assets/js/vendor.min.js"></script>

   <!-- KNOB JS -->
   <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
   <!-- Chart JS -->
   <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

   <!-- Jvector map -->
   <script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
   <script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>

   <!-- Datatable js -->
   <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
   <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
   <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
   <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

   <!-- Dashboard Init JS -->
   <script src="assets/js/pages/dashboard.init.js"></script>

   <!-- App js -->
   <script src="assets/js/app.min.js"></script>