<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">

                        <h4 class="page-title">Liste des Absences</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-12">
                    <div class="card-box">
                        <?php if ($modif_ok == 1) { ?>
                            <div class="alert alert-success" role="alert">
                                La modification à bien été effectué!
                            </div>
                        <?php } ?>
                        <!-- <?php if ($SessionAdmin == 1) { ?>
                                        <div class="alert alert-danger" role="alert">
                                           <?php echo '<span class="font-weight-bold">' . $_SESSION['admin_email'] . '</span> est Connecter !! Ne peut pas être Supprimer !! ' ?>
                                        </div>
                                        <?php } ?> -->


                        <table id="datatable" class="table table-bordered dt-responsive nowrap table-striped">
                            <thead>
                                <tr>
                                    <th>Nom enseignant</th>
                                    <th>Date de début</th>
                                    <th>Date de fin</th>
                                    <th>Durée</th>
                                    <th>Options</th>
                                </tr>
                            </thead>


                            <tbody>
                                <?php foreach ($absence as $abs) { ?>


                                    <tr>
                                        <td><?php echo $abs['enseignant_nom'] ?></td>
                                        <td><?php echo date("d/m/Y", strtotime($abs['debut'])) ?></td>
                                        <td><?php echo date("d/m/Y", strtotime($abs['fin'])) ?></td>
                                        <!-- calcule le nombre de secondes entre les deux dates, puis divise ce nombre par 86400 (le nombre de secondes dans un jour) pour obtenir le nombre de jours, et enfin utilise la fonction "floor" pour arrondir ce nombre à l'entier inférieur
                                        On ajoute 1 pour compter le jour de début dans le calcul de la durée -->
                                        <td><?php echo floor((strtotime($abs['fin']) - strtotime($abs['debut'])) / 86400) + 1; ?> jours</td>
                                        <td>
                                            <a href="modifier_absence.php?id=<?php echo $abs['id'] ?>" class="btn btn-primary waves-effect waves-light"> <i class="mdi mdi-pencil"></i> <span>Modifier</span> </a>

                                            <a href="supprimer_absence.php?id=<?php echo $abs['id'] ?>" onclick="return confirm('Etes vous sur de vouloir Supprimer cet absence?')" class="btn btn-pink waves-effect waves-light"> <i class="mdi mdi-trash-can"></i> <span>Supprimer</span> </a>
                                        </td>
                                    </tr>

                                <?php  }  ?>
                            </tbody>
                        </table>
                    </div> <!-- end card-box -->
                </div> <!-- end col -->
            </div> <!-- end row -->



        </div> <!-- container-fluid -->

    </div> <!-- content -->

    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 text-center">
                    2023 &copy; thème Greeva, créé par Coderthemes, modifié par Véricel Grégory. 
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->

</div>

<script src="assets/js/vendor.min.js"></script>

<!-- datatable js -->
<script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
<script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
<script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
<script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

<script src="assets/libs/datatables/dataTables.buttons.min.js"></script>
<script src="assets/libs/datatables/buttons.bootstrap4.min.js"></script>
<script src="assets/libs/datatables/buttons.html5.min.js"></script>
<script src="assets/libs/datatables/buttons.flash.min.js"></script>
<script src="assets/libs/datatables/buttons.print.min.js"></script>

<script src="assets/libs/datatables/dataTables.keyTable.min.js"></script>
<script src="assets/libs/datatables/dataTables.select.min.js"></script>

<!-- Datatables init -->
<script src="assets/js/pages/datatables.init.js"></script>

<!-- App js -->
<script src="assets/js/app.min.js"></script>