   <div class="content-page">
       <div class="content">

           <!-- Start Content-->
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box">

                           <h4 class="page-title">Ajouter une activitées ou une information</h4>
                       </div>
                   </div>
               </div>
               <!-- end page title -->

               <div class="row">
                   <div class="col-12">
                       <div class="card-box">
                           <form class="form-horizontal" method="POST">
                               <h4 class="d-flex justify-content-center align-items-center page-title">
                                   <div class="form-check form-check-inline form-check-lg">
                                       <input class="form-check-input" type="radio" name="type" id="activite" value="activite" onclick="toggleInputs(true)" checked>
                                       <label class="form-check-label" for="activite">Activité</label>
                                   </div>
                                   <div class="form-check form-check-inline form-check-lg">
                                       <input class="form-check-input" type="radio" name="type" id="information" value="information" onclick="toggleInputs(false)">
                                       <label class="form-check-label" for="information">Information</label>
                                   </div>
                               </h4><br>
                               <?php if ($ajout_ok == 1) { ?>
                                   <div class="alert alert-success" role="alert">
                                       <?php echo 'L\'activité ' . '<span class="font-weight-bold">' . $_POST['titre'] . '</span>' . ' a bien été ajouté' ?>
                                   </div>
                               <?php } else if ($ajout_ok == 2) { ?>
                                   <div class="alert alert-success" role="alert">
                                       <?php echo 'L\'information ' . '<span class="font-weight-bold">' . $_POST['titre'] . '</span>' . ' a bien été ajouté' ?>
                                   </div>
                               <?php } else if ($ajout_ok == 3) { ?>
                                   <div class="alert alert-danger" role="alert">
                                       <?php echo 'L\'activité ' . '<span class="font-weight-bold">' . $_POST['titre'] . '</span>' . ' existe déjà pour le ' . '<span class="font-weight-bold">'  . date("d/m/Y", strtotime($_POST['date'])) . '</span>' . ' et cette classe ' ?>
                                   </div>
                               <?php } ?>

                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="titre" id="titreGeneral">Titre</label>
                                   <div class="col-sm-10">
                                       <input type="text" class="form-control" id="titre" name="titre" required>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="description">Description</label>
                                   <div class="col-sm-10">
                                       <textarea type="text" class="form-control" id="description" name="description"></textarea>
                                   </div>
                               </div>
                               <div class="form-row">
                                   <div class="col" id="datetime-input">
                                       <div class="form-group row">
                                           <label class="col-sm-2 col-form-label" for="date">Date</label>
                                           <div class="col-sm-4">
                                               <input type="date" class="form-control" id="date" name="date" lang="fr" value="2023-02-19">
                                           </div>
                                           <label class="col-sm-1 col-form-label" for="duree">Durée</label>
                                           <div class="col-sm-5">
                                               <input type="text" class="form-control" id="duree" name="duree">
                                           </div>
                                       </div>
                                   </div>
                               </div>


                               <div class="form-group row">
                                   <label for="hori-pass1" class="col-sm-2 col-form-label">Classe<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <select name="id_classe" id="selectClasse" class="form-control" required>
                                           <option value="">Sélectionnez une classe</option>
                                           <?php foreach ($listeClasse as $classe) { ?>
                                               <option value="<?php echo $classe['id'] ?>"><?php echo $classe['nom'] ?> niveau <?php echo $classe['niveau'] ?> </option>
                                           <?php } ?>
                                       </select>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <div class="col-sm-12">
                                       <button type="submit" class="btn btn-primary" name="ajouter">Ajouter</button>
                                   </div>
                               </div>
                           </form>
                       </div>
                   </div>
               </div><!-- end row -->
           </div> <!-- container-fluid -->

       </div> <!-- content -->

       <!-- Footer Start -->
       <footer class="footer">
           <div class="container-fluid">
               <div class="row">
                   <div class="col-md-12 text-center">
                       2023 &copy; thème Greeva, créé par Coderthemes, modifié par Véricel Grégory. 
                   </div>
               </div>
           </div>
       </footer>
       <!-- end Footer -->

   </div>



   <!-- Vendor js -->
   <script src="assets/js/vendor.min.js"></script>

   <!-- KNOB JS -->
   <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
   <!-- Chart JS -->
   <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

   <!-- Jvector map -->
   <script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
   <script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>

   <!-- Datatable js -->
   <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
   <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
   <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
   <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

   <!-- Dashboard Init JS -->
   <script src="assets/js/pages/dashboard.init.js"></script>

   <!-- App js -->
   <script src="assets/js/app.min.js"></script>

   <!-- function password-->
   <script src="assets/js/password.js"></script>

   <script>
       function toggleInputs() {
           var type = document.querySelector('input[name="type"]:checked').value;
           var dateTimeInput = document.getElementById("datetime-input");
           var titreGeneral = document.getElementById("titreGeneral");

           if (type === "information") {
               dateTimeInput.style.display = "none";
               titreGeneral.innerHTML = "Titre de l'information<span class='text-danger'>*</span>";
           } else {
               dateTimeInput.style.display = "block";
               titreGeneral.innerHTML = "Titre de l'activité<span class='text-danger'>*</span>";
           }
       }
   </script>