<div class="content-page" style="height:auto; background-image: url('./assets/images/sous-main2.jpg'); background-size: cover; background-position: center;">

    <!-- Start Content-->
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-flex align-items-center">
                    <h4 class="page-title mr-auto">Tableau de Bord</h4>
                    <ol class="breadcrumb">
                        <li id="date" class="breadcrumb-item active"></li>
                        <li id="time" class="breadcrumb-item active"></li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row" class="calendar wrapper">
            <div class="col-xl-4 offset-xl-2" style="background-color: transparent;">

                <div class="mb-3 mt-4 ">
                    <div id="calendar"></div>
                </div>


            </div> <!-- end col -->
        </div> <!-- container -->

        <!-- Footer Start -->
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 text-center">
                        2023 &copy; thème Greeva, créé par Coderthemes, modifié par Véricel Grégory. 
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->

    </div>
    <!-- end container-fluid -->
    <!-- Vendor js -->
    <script src="assets/js/vendor.min.js"></script>

    <!-- KNOB JS -->
    <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
    <!-- Chart JS -->
    <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

    <!-- Datatable js -->
    <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
    <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
    <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
    <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>


    <!-- App js -->
    <script src="assets/js/app.min.js"></script>

    <!-- Date -->
    <script src="assets/js/board.js"></script>