<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">

                        <h4 class="page-title">Liste des Enseignants</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-12">
                    <div class="card-box">
                        <!-- <?php if ($SessionAdmin == 1) { ?>
                                        <div class="alert alert-danger" role="alert">
                                           <?php echo '<span class="font-weight-bold">' . $_SESSION['admin_email'] . '</span> est Connecter !! Ne peut pas être Supprimer !! ' ?>
                                        </div>
                                        <?php } ?> -->


                        <table id="datatable" class="table table-bordered dt-responsive nowrap table-striped">
                            <thead>
                                <tr>
                                    <th>Nom enseignant</th>
                                    <th>Email enseignant</th>
                                    <th>Classe</th>
                                    <th>Niveau</th>
                                    <th>Options</th>
                                </tr>
                            </thead>


                            <tbody>
                                <?php foreach ($enseignants as $prof) { ?>


                                    <tr>
                                        <td><?php echo $prof['nom_enseignant'] ?></td>
                                        <td><?php echo $prof['email'] ?></td>
                                        <td><?php echo $prof['nom_classe'] ?></td>
                                        <td><?php echo $prof['niveau_classe'] ?></td>
                                        <td>
                                            <a href="enseignant_liste.php?del=<?php echo $prof['id'] ?> " onclick="return confirm('Voulez-vous vraiment supprimer cet enseignant ? ?')" class="btn btn-pink waves-effect waves-light" id="Delete"> <i class="mdi mdi-trash-can"></i> <span>Supprimer</span> </a>
                                        </td>
                                    </tr>

                                <?php  }  ?>
                            </tbody>
                        </table>
                    </div> <!-- end card-box -->
                </div> <!-- end col -->
            </div> <!-- end row -->



        </div> <!-- container-fluid -->

    </div> <!-- content -->

    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 text-center">
                    2023 &copy; thème Greeva, créé par Coderthemes, modifié par Véricel Grégory. 
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->

</div>

<script src="assets/js/vendor.min.js"></script>

<!-- datatable js -->
<script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
<script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
<script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
<script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

<script src="assets/libs/datatables/dataTables.buttons.min.js"></script>
<script src="assets/libs/datatables/buttons.bootstrap4.min.js"></script>
<script src="assets/libs/datatables/buttons.html5.min.js"></script>
<script src="assets/libs/datatables/buttons.flash.min.js"></script>
<script src="assets/libs/datatables/buttons.print.min.js"></script>

<script src="assets/libs/datatables/dataTables.keyTable.min.js"></script>
<script src="assets/libs/datatables/dataTables.select.min.js"></script>

<!-- Datatables init -->
<script src="assets/js/pages/datatables.init.js"></script>

<!-- App js -->
<script src="assets/js/app.min.js"></script>