   <div class="content-page">
       <div class="content">

           <!-- Start Content-->
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box">

                           <h4 class="page-title">Ajouter un Enseignant</h4>
                       </div>
                   </div>
               </div>
               <!-- end page title -->

               <div class="row">
                   <div class="col-12">
                       <div class="card-box">
                           <?php if ($ajout_ok == 1) { ?>
                               <div class="alert alert-success" role="alert">
                                   <?php echo 'L\'enseignant avec l\'email ' . '<span class="font-weight-bold">' . $_POST['email'] . '</span>' . ' à bien été ajouté' ?>
                               </div>
                           <?php } else if ($ajout_ok == 2) { ?>
                               <div class="alert alert-danger" role="alert">
                                   <?php echo 'Un enseignant avec l\'email ' . '<span class="font-weight-bold">' . $_POST['email'] . '</span>' . ' éxiste déja' ?>
                               </div>
                           <?php } else if ($ajout_ok == 3) { ?>
                               <div class="alert alert-danger" role="alert">
                                   <?php echo 'Le mot de passe doit contenir au moins 8 caractères avec au moins 1 majuscule, 1 minuscule, 1 chiffre et 1 caractère spécial (@$!%*#?&)' ?>
                               </div>
                           <?php } ?>

                           <form class="form-horizontal" method="POST">
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="nomEnseignant">Nom de l'enseignant<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="text" class="form-control" id="nomEnseignant" name="nomEnseignant" required>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="email">Email de l'utilisateur<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="text" class="form-control" id="email" name="email" required>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="passwordEnseignant">Mot de passe<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="password" class="form-control" id="passwordEnseignant" name="password" required>
                                   </div>
                                   <span class="col-sm-2"></span>
                                   <div class=" col-sm-10">
                                       <input type="checkbox" id="chkPasswordEnseignant">
                                       <label for="insShowPassword" id="lblPasswordEnseignant">Afficher le mot de passe</label><br><br>
                                   </div>
                               </div>
                               <button type="submit" class="btn btn-primary" name="ajouter">Ajouter</button>
                           </form>

                       </div> <!-- end card-box -->
                   </div><!-- end col -->
               </div>
               <!-- end row -->




           </div> <!-- container-fluid -->

       </div> <!-- content -->

       <!-- Footer Start -->
       <footer class="footer">
           <div class="container-fluid">
               <div class="row">
                   <div class="col-md-12 text-center">
                       2023 &copy; thème Greeva, créé par Coderthemes, modifié par Véricel Grégory. 
                   </div>
               </div>
           </div>
       </footer>
       <!-- end Footer -->

   </div>
   <!-- Vendor js -->
   <script src="assets/js/vendor.min.js"></script>

   <!-- KNOB JS -->
   <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
   <!-- Chart JS -->
   <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

   <!-- Jvector map -->
   <script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
   <script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>

   <!-- Datatable js -->
   <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
   <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
   <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
   <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

   <!-- Dashboard Init JS -->
   <script src="assets/js/pages/dashboard.init.js"></script>

   <!-- App js -->
   <script src="assets/js/app.min.js"></script>

   <!-- function password-->
   <script src="assets/js/password.js"></script>