<div class="row">
    <div class="col-12">
        <div class="card-box">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="type" id="activite" value="activite" checked>
                <label class="form-check-label" for="activite">
                    Activité
                </label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="type" id="information" value="information">
                <label class="form-check-label" for="information">
                    Information
                </label>
            </div>
            <?php if ($ajout_ok == 1) { ?>
                <div class="alert alert-success" role="alert">
                    <?php echo 'L\'activité ou l\'information ' . '<span class="font-weight-bold">' . $_POST['titre'] . '</span>' . ' a bien été ajouté' ?>
                </div>
            <?php } else if ($ajout_ok == 2) { ?>
                <div class="alert alert-danger" role="alert">
                    <?php echo 'L\'activité ou l\'information ' . '<span class="font-weight-bold">' . $_POST['titre'] . '</span>' . ' existe déjà avec ce titre à cette date' ?>
                </div>
            <?php } ?>
            <form class="form-horizontal" method="POST">
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="titre">Titre de l'activité ou de l'information<span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="titre" name="titre" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="description">Description</label>
                    <div class="col-sm-10">
                        <textarea type="text" class="form-control" id="description" name="description"></textarea>
                    </div>
                </div>
                <div class="form-group row date-duree-group" style="display:none;">
                    <label class="col-sm-2 col-form-label" for="date">Date</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control" id="date" name="date">
                    </div>
                </div>
                <div class="form-group row date-duree-group" style="display:none;">
                    <label class="col-sm-2 col-form-label" for="duree">Durée</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="duree" name="duree">
                    </div>
                </div>
                <input type="hidden" id="date" name="date">
                <input type="hidden" id="duree" name="duree">
                <div class="form-group row" <?php if ($type === "information") { ?> style="display: none;" <?php } ?>>
                    <label class="col-sm-2 col-form-label" for="date">Date</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control" id="date" name="date">
                    </div>
                </div>
                <div class="form-group row" <?php if ($type === "information") { ?> style="display: none;" <?php } ?>>
                    <label class="col-sm-2 col-form-label" for="duree">Durée</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="duree" name="duree">
                    </div>
                </div>