   <div class="content-page">
       <div class="content">

           <!-- Start Content-->
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box">

                           <h4 class="page-title">Ajouter des photos</h4>
                       </div>
                   </div>
               </div>
               <!-- end page title -->

               <div class="row">
                   <div class="col-12">
                       <div class="card-box">
                           <?php if ($ajout_ok == 1) { ?>
                               <div class="alert alert-success" role="alert">
                                   <?php echo 'Le fichier a été téléchargé avec succès.' ?>
                               </div>
                           <?php } else if ($ajout_ok == 2) { ?>
                               <div class="alert alert-danger" role="alert">
                                   <?php echo 'Une erreur s\'est produite lors du téléchargement du fichier.' ?>
                               </div>
                           <?php } else if ($ajout_ok == 3) { ?>
                               <div class="alert alert-danger" role="alert">
                                   <?php echo 'La taille du fichier est trop grande (5MB max).' ?>
                               </div>
                           <?php } else if ($ajout_ok == 4) { ?>
                               <div class="alert alert-danger" role="alert">
                                   <?php echo 'Le type de fichier n\'est pas autorisé (JPEG, PNG et GIF seulement).' ?>
                               </div>
                           <?php } ?>
                           <form class="form-horizontal" action="galerie_ajouter.php" method="post" enctype="multipart/form-data">
                               <div class="form-group row">
                                   <label for="hori-pass1" class="col-sm-2 col-form-label">Sélectionnez la classe :<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <select name="nom_classe" class="form-control" required>
                                           <?php foreach ($listeClasse as $classe) { ?>
                                               <option name="id_classe" value="<?php echo $classe['nom'] ?>"><?php echo $classe['nom'] ?>, niveau <?php echo $classe['niveau'] ?></option>
                                           <?php } ?>
                                       </select>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="photo">Choisissez la photo:<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="file" class="form-control" id="photo" name="photo" required>
                                   </div>
                               </div>
                               <button type="submit" class="btn btn-primary" name="ajouter">Ajouter</button>
                           </form>

                       </div>


                   </div> <!-- end card-box -->
               </div><!-- end col -->
           </div>
           <!-- end row -->




       </div> <!-- container-fluid -->

   </div> <!-- content -->

   <!-- Footer Start -->
   <footer class="footer">
       <div class="container-fluid">
           <div class="row">
               <div class="col-md-12 text-center">
                   2023 &copy; thème Greeva, créé par Coderthemes, modifié par Véricel Grégory. 
               </div>
           </div>
       </div>
   </footer>
   <!-- end Footer -->

   </div>
   <!-- Vendor js -->
   <script src="assets/js/vendor.min.js"></script>

   <!-- KNOB JS -->
   <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
   <!-- Chart JS -->
   <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

   <!-- Jvector map -->
   <script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
   <script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>

   <!-- Datatable js -->
   <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
   <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
   <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
   <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

   <!-- Dashboard Init JS -->
   <script src="assets/js/pages/dashboard.init.js"></script>

   <!-- App js -->
   <script src="assets/js/app.min.js"></script>