<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>Administration de l'école Jules Ferry d'Ambérieu-en-Bugey</title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!--Favicon-->
  <link rel="shortcut icon" href="../img/favicon/icons8-school-smashingstocks-flat-96.png" />
  <!-- CSS Files -->
  <link rel="stylesheet" href="../css/normalize.css" />
  <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
  <link href="assets/css/app.min.css" rel="stylesheet" type="text/css" />
  <link id="pagestyle" href="assets/css/material-dashboard.css" rel="stylesheet" />
  <link href="assets/css/monstyle.css" rel="stylesheet" type="text/css" />
</head>

<body class="bg-light">
  <main class="main-content mt-0">
    <div class="page-header align-items-start min-vh-100">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">
                    Connexion
                  </h4>
                </div>
              </div>
              <div class="card-body">
                <form role="form" method="POST" class="text-start">
                  <?php if ($connexion_error == 1) { ?>
                    <div class="alert alert-danger" role="alert">
                      Admin Ou Mot De Passe Incorect !! Veuiller rééssayer !!!
                    </div>
                  <?php } ?>
                  <div class="input-group input-group-outline my-3">
                    <label class="form-label">Email</label>
                    <input type="email" name="email" id="email" class="form-control" />
                  </div>
                  <div class="input-group input-group-outline mb-3">
                    <label class="form-label">Mot de passe</label>
                    <input type="password" name="password" id="password" class="form-control" />
                  </div>
                  <div class="form-check form-switch d-flex align-items-center mb-3">
                    <input class="form-check-input" type="checkbox" id="chkPasswordVisible" />
                    <label class="form-check-label mb-0 ms-3" for="passwordVisible" id="lblPasswordVisible">Afficher le mot de passe</label>
                  </div>
                  <div class="form-check form-switch d-flex align-items-center mb-3">
                    <input class="form-check-input" type="checkbox" id="rememberMe" />
                    <label class="form-check-label mb-0 ms-3" for="rememberMe" id="lbpRememberMe">Se souvenir de moi</label>
                  </div>
                  <div class="text-center">
                    <button name="login" id="login" type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">
                      Connexion
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer position-absolute bottom-2 py-2 w-100">
        <div class="container">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-12 col-md-6 my-auto">
              <div class="copyright text-center text-sm text-white text-lg-start">
                ©
                <script>
                  document.write(new Date().getFullYear());
                </script>
                , made by VERICODE.
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>
  <!--   Core JS Files   -->
  <!-- <script src="../js/bootstrap.bundle.min.js"></script> -->
  <script src="../js/jquery.min.js"></script>
  <script src="./assets/js/index.js"></script>
</body>

</html>