<?php
if (!isset($_SESSION['admin_email']) || $_SESSION['admin_email'] == '') {
    header('location:index.php');
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Partie administrative du projet de gestion d'école</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="../img/favicon/icons8-school-smashingstocks-flat-16.png">

    <!-- DataTables -->
    <link href="assets/libs/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/libs/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <!-- App css -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/app.min.css" rel="stylesheet" type="text/css" />

    <!-- Inclusion de Chart.js -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <!-- <link href="assets/css/monstyle.css" rel="stylesheet" type="text/css" /> -->
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.4/index.global.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/locale/fr.js"></script>


    <script src="./assets/fullcalendar/core/index.global.js"></script>
    <script src='./assets/fullcalendar/daygrid/index.global.js'></script>
    <script src="./assets/calendrier/calendrier.js"></script>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script> -->
    <style>
        #sidebar-menu li a:hover {
            background-color: #f2f2f2;
        }

        .wrapper {
            width: 90%;
            height: 850px;
            margin: 0 auto;
        }
    </style>
</head>

<body onload="toggleInputs()">

    <!-- Begin page -->
    <div id="wrapper">

        <!-- Topbar Start -->
        <div class="navbar-custom">
            <ul class="list-unstyled topnav-menu float-right mb-0">
                <li class="dropdown notification-list">
                    <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                        <img src="assets/images/users/avatar-4.jpg" alt="user-image" class="rounded-circle">
                        <span class="pro-user-name ml-1">
                            <?php echo $_SESSION['admin_email'] ?> <i class="mdi mdi-chevron-down"></i>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                        <!-- item-->
                        <div class="dropdown-item noti-title">
                            <h6 class="m-0">
                                Bienvenue !
                            </h6>
                        </div>

                        <!-- item-->
                        <a href="./compteAdmin.php" class="dropdown-item notify-item">
                            <i class="dripicons-user"></i>
                            <span>Mon compte</span>
                        </a>

                        <!-- item-->
                        <a href="./support.php" class="dropdown-item notify-item">
                            <i class="dripicons-help"></i>
                            <span>Support</span>
                        </a>

                        <div class="dropdown-divider"></div>

                        <!-- item-->
                        <a href="deco_admin.php" class="dropdown-item notify-item">
                            <i class="dripicons-power"></i>
                            <span>Déconnexion</span>
                        </a>

                    </div>
                </li>
            </ul>

            <ul class="list-unstyled menu-left mb-0">
                <li class="float-left">
                    <a href="board.php" class="logo">
                        <span class="logo-lg">
                            <img src="assets/images/mon_ecole2.jpg" alt="" height="65" width="150">
                        </span>
                        <span class="logo-sm">
                            <img src="assets/images/favicon96.png" alt="" height="24">
                        </span>
                    </a>
                </li>
                <li class="float-left">
                    <a class="button-menu-mobile navbar-toggle">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        <!-- end Topbar -->

        <!-- ========== Left Sidebar Start ========== -->
        <div class="left-side-menu">

            <div class="slimscroll-menu">

                <!--- Sidemenu -->
                <div id="sidebar-menu">

                    <ul class="metismenu" id="side-menu">

                        <li class="menu-title">Navigation</li>

                        <li>
                            <a href="board.php">
                                <i class="dripicons-meter"></i>
                                <span> Tableau de bord </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript: void(0);">
                                <i class="dripicons-list"></i>
                                <span> Administrateur </span>
                                <span class="menu-arrow"></span>
                            </a>
                            <ul class="nav-second-level" aria-expanded="false">
                                <li>
                                    <a href="admin_liste.php">Liste des administrateurs</a>
                                </li>
                                <li>
                                    <a href="admin_ajouter.php">Ajouter un administrateur</a>
                                </li>
                                <li>
                                    <a href="compteAdmin.php">Mon compte</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript: void(0);">
                                <i class="dripicons-list"></i>
                                <span> Enseignants </span>
                                <span class="menu-arrow"></span>
                            </a>
                            <ul class="nav-second-level" aria-expanded="false">
                                <li>
                                    <a href="enseignant_liste.php">Liste des enseignants</a>
                                </li>
                                <li>
                                    <a href="enseignant_ajouter.php">Ajouter un enseignant</a>
                                </li>
                                <li>
                                    <a href="absence_ajouter.php">Ajouter une absence</a>
                                </li>
                                <li>
                                    <a href="absence_liste.php">Liste des absences</a>
                                </li>
                            </ul>
                        </li>


                        <li>
                            <a href="javascript: void(0);">
                                <i class="dripicons-list"></i>
                                <span> Classes </span>
                                <span class="menu-arrow"></span>
                            </a>
                            <ul class="nav-second-level" aria-expanded="false">
                                <li>
                                    <a href="classe_liste.php">Liste des classes</a>
                                </li>
                                <li>
                                    <a href="classe_ajouter.php">Ajouter une classe</a>
                                </li>
                                <li>
                                    <a href="activitees_ajouter.php">Ajouter une activité ou une information</a>
                                </li>
                                <li>
                                    <a href="activitees_liste.php">Liste des activitées et des informations</a>
                                </li>
                                <li>
                                    <a href="galerie_ajouter.php">Ajouté des photos</a>
                                </li>
                                <li>
                                    <a href="galerie_liste2.php">Liste des photos</a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="javascript: void(0);">
                                <i class="dripicons-list"></i>
                                <span> Elèves </span>
                                <span class="menu-arrow"></span>
                            </a>
                            <ul class="nav-second-level" aria-expanded="false">
                                <li>
                                    <a href="eleve_liste.php">Liste des élèves</a>
                                </li>
                                <li>
                                    <a href="eleve_ajouter.php">Ajouter un élève</a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="javascript: void(0);">
                                <i class="dripicons-list"></i>
                                <span> Parents </span>
                                <span class="menu-arrow"></span>
                            </a>
                            <ul class="nav-second-level" aria-expanded="false">
                                <li>
                                    <a href="parents_liste.php">Liste des parents</a>
                                </li>
                                <li>
                                    <a href="parents_ajouter.php">Ajouter un parent</a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                </div>
                <!-- End Sidebar -->

                <div class="clearfix"></div>

            </div>
            <!-- Sidebar -left -->

        </div>
        <!-- Left Sidebar End -->






        <?php include $template . '.phtml' ?>





    </div>
    <!-- END wrapper -->


    <!-- Right bar overlay-->
    <div class="rightbar-overlay"></div>



</body>

</html>