   <div class="content-page">
       <div class="content">

           <!-- Start Content-->
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box">

                           <h4 class="page-title">Modifier une activité</h4>
                       </div>
                   </div>
               </div>
               <!-- end page title -->

               <div class="row">
                   <div class="col-12">
                       <div class="card-box">
                           <?php if ($modif_ok == 1) { ?>
                               <div class="alert alert-success" role="alert">
                                   La modification a bien été effectué!
                               </div>
                           <?php } ?>
                           <form class="form-horizontal" method="POST">
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="simpleinput">Titre<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="text" value="<?php echo $activitees_modifier['titreActivitees']; ?>" class="form-control" id="simpleinput" name="titreActivitees" required>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="simpleinput">Description</label>
                                   <div class="col-sm-10">
                                       <input type="text" value="<?php echo $activitees_modifier['description']; ?>" class="form-control" id="simpleinput" name="description" riquired>
                                   </div>
                               </div>
                               <div class="form-row">
                                   <div class="col" id="datetime-input">
                                       <div class="form-group row">
                                           <label class="col-sm-2 col-form-label" for="date">Date</label>
                                           <div class="col-sm-4">
                                               <input type="date" value="<?php echo $activitees_modifier['jours']; ?>" class=" form-control" id="date" name="date">
                                           </div>
                                           <label class="col-sm-1 col-form-label" for="duree">Durée</label>
                                           <div class="col-sm-5">
                                               <input type="text" value="<?php echo $activitees_modifier['duree']; ?>" class=" form-control" id="duree" name="duree">
                                           </div>
                                       </div>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label for="hori-pass1" class="col-sm-2 col-form-label">Classe<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <select name="id_classe" class="form-control">
                                           <?php foreach ($listeClasse as $classe) { ?>
                                               <option <?php if ($classe['id'] == $activitees_modifier['id_classe']) {
                                                            echo "selected";
                                                        } ?> value="<?php echo $classe['id'] ?>"><?php echo $classe['nom'] ?> </option>
                                           <?php } ?>
                                       </select>
                                   </div>
                               </div>

                               <button type="submit" class="btn btn-primary" name="modifier_activitees">Modifier</button>
                               <a href="activitees_liste.php" class="btn btn-pink waves-effect waves-light"> <i class="mdi mdi-trash-can"></i> <span>Annulé</span> </a>
                           </form>

                       </div> <!-- end card-box -->
                   </div><!-- end col -->
               </div>
               <!-- end row -->




           </div> <!-- container-fluid -->

       </div> <!-- content -->

       <!-- Footer Start -->
       <footer class="footer">
           <div class="container-fluid">
               <div class="row">
                   <div class="col-md-12 text-center">
                       2023 &copy; thème Greeva, créé par Coderthemes, modifié par Véricel Grégory. 
                   </div>
               </div>
           </div>
       </footer>
       <!-- end Footer -->

   </div>
   <!-- Vendor js -->
   <script src="assets/js/vendor.min.js"></script>

   <!-- KNOB JS -->
   <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
   <!-- Chart JS -->
   <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

   <!-- Jvector map -->
   <script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
   <script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>

   <!-- Datatable js -->
   <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
   <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
   <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
   <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

   <!-- Dashboard Init JS -->
   <script src="assets/js/pages/dashboard.init.js"></script>

   <!-- App js -->
   <script src="assets/js/app.min.js"></script>