   <div class="content-page">
       <div class="content">

           <!-- Start Content-->
           <div class="container-fluid">

               <!-- start page title -->
               <div class="row">
                   <div class="col-12">
                       <div class="page-title-box">

                           <h4 class="page-title">Modifier un parent</h4>
                       </div>
                   </div>
               </div>
               <!-- end page title -->

               <div class="row">
                   <div class="col-12">
                       <div class="card-box">
                           <?php if ($modif_ok == 1) { ?>
                               <div class="alert alert-success" role="alert">
                                   La modification a bien été effectué!
                               </div>
                           <?php } ?>
                           <form class="form-horizontal" method="POST">
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="simpleinput">Nom<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="text" value="<?php echo $parent_modifier['nom']; ?>" class="form-control" name="nom" required>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="simpleinput">Prénom<span class="text-danger">*</span></label>
                                   <div class="col-sm-10">
                                       <input type="text" value="<?php echo $parent_modifier['prenom']; ?>" class="form-control" name="prenom" riquired>
                                   </div>
                               </div>
                               <div class="form-group row">
                                   <label class="col-sm-2 col-form-label" for="simpleinput">Email</label>
                                   <div class="col-sm-10">
                                       <input type="email" value="<?php echo $parent_modifier['email']; ?>" class="form-control" name="email" required>
                                   </div>
                               </div>
                               <button type="submit" class="btn btn-primary" name="modifier">Modifier</button>
                               <a href="parents_liste.php" class="btn btn-pink waves-effect waves-light"> <i class="mdi mdi-trash-can"></i> <span>Annulé</span> </a>
                           </form>

                       </div> <!-- end card-box -->
                   </div><!-- end col -->
               </div>
               <!-- end row -->




           </div> <!-- container-fluid -->

       </div> <!-- content -->

       <!-- Footer Start -->
       <footer class="footer">
           <div class="container-fluid">
               <div class="row">
                   <div class="col-md-12 text-center">
                   </div>
               </div>
           </div>
       </footer>
       <!-- end Footer -->

   </div>
   <!-- Vendor js -->
   <script src="assets/js/vendor.min.js"></script>

   <!-- KNOB JS -->
   <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
   <!-- Chart JS -->
   <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

   <!-- Jvector map -->
   <script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
   <script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>

   <!-- Datatable js -->
   <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
   <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
   <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
   <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>

   <!-- Dashboard Init JS -->
   <script src="assets/js/pages/dashboard.init.js"></script>

   <!-- App js -->
   <script src="assets/js/app.min.js"></script>